= E-ARK DIP Specification

This repository holds information about the Dissemination Information Package (DIP) format specification maintained by the Digital Information LifeCycle Interoperability Standards Board (http://www.dilcis.eu/).

== The specification

=== Final versions

Final versions of the specification are published at the http://dilcis.eu/specifications/dip[DILCIS Board web site] as PDFs.

=== Draft versions

The most up-to-date version of the DIP specification is managed as an https://asciidoc.org/[Asciidoc] document. The root document is held in the link:./specification/eark-dip.adoc[./specification/eark-dip.adoc] file.

This is a draft version of the specification that is being collaboratively edited by multiple experts.

== Previous versions of the specification

Previous versions of the specification are available on the link:./archive/[archive] folder.

== Objectives

Key objectives of this specification are:

* To define a generic structure of the DIP format in a way that it is suitable for a wide variety of archival records, such as document and image collections, databases or geographical data.
* To recommend a set of metadata related to the structural and the access aspects of the DIP.

== Target audience

The target audiences for this specification are archival institutions and software providers that are willing to implement or update their DIP format specification.

== Join the party

If you are interested engage more with this specification and the people and organizations behind it - feel free to:

* use the https://help.github.com/articles/watching-and-unwatching-repositories/[GitHub Watch-function].
* ask questions or report your thoughts and findings via the https://github.com/DILCISBoard/E-ARK-DIP/issues[Issues function].
* visit http://dilcis.eu/[DILCIS Board web site] and contact members.
