[chapter]
= Content Information Types

Content Information is _"`A set of information that is the original target of preservation or
that includes part or all of that information. It is an Information Object composed of its Content
Data Object and its Representation Information_`" according to the OAIS Reference Model.

A Content Information Type can therefore be understood as a category of Content Information, for example
relational databases, scientific data, electronic records management systems, digitised maps, etc..

According to the Common Specification for Information Package it is possible to http://earkcsip.dilcis.eu/#61-content-information-type-specifications[create specifications for
Content Information Types]. It is within these specifications that requirements and descriptions related to the specific Content Information Type is described. The DIP specification can not describe how each Content Information Type should be disseminated and therefore the DIP specification sets out requirements on how Content Information Type specifications should handle DIP requirements.

* A Content Information Type specification should have a section which sole focus is on describing DIP requirements and/or recommendations
 ** The DIP section should describe how to read/edit access rights
 ** The DIP section should describe how to register access software
 ** The DIP section could mention and list relevant access software for the Content Information Type

