= E-ARK DIP Specification source

This directory holds the https://asciidoc.org/[Asciidoc] source files for the E-ARK DIP specification. The top-level document is link:eark-dip.adoc[`eark-dip.adoc`], which includes the other sub-documents in the correct order.

Tables and appendices are included as separate files which are generated by the spec-publisher tool. This is a git sub-repo in the project root directory, link:../spec-publisher/pom.xml[`spec-publisher`]. If you have Java and Maven, you can produce the tables and appendices with the following commands:

[source,bash]
----
mvn package -f spec-publisher/pom.xml
java -jar spec-publisher/target/mets-profile-processor-0.2.0-SNAPSHOT.jar \
     -f specification.yaml \
     -o specification \
     profile/E-ARK-DIP-v2-2-0.xml
----

The generated files will be placed in the `specification` directory, in the `tables` and `appendices` subdirectories. If you have https://asciidoctor.org[Asciidoctor] installed, you can convert the Asciidoc files to other formats (e.g., HTML, PDF) using the following command:

[source,bash]
----
asciidoctor -o output.html specification/eark-dip.adoc
----
